version: 0.2

phases:
  build:
    commands:
      - cd components/server
      - npm install
      - npm run lint
      - npm run compile
      - npm run unit-tests
      # - npm run setup-integration-tests
      # - npm run integration-test
      - cd client
      - npm install
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "components/server"
