# Set the version of docker compose to use
version: "3.9"

# The containers that compose the project
services:
  db:
    image: postgres:13
    restart: always
    container_name: test-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: testdb
#   redis:
#     image: redis:6.2-alpine
#     restart: always
#     hostname: redis
#     ports:
#       - '6379:6379'
#     command: redis-server --save 20 1 --loglevel warning
#     volumes:
#       - cache:/data
# volumes:
#   cache:
#     driver: local
